name: $(Year:yyyy).$(Month).$(DayOfMonth).$(rev:r)

resources:
  pipelines:
  - pipeline: progressive-web-app
    source: \microsoft-account-profile-information\progressive-web-app
    trigger: 
      branches:
        include: 
        - main

trigger: none

pr: none

variables:
  - group: 'Progressive Web Application'

stages:

- template: ../../../.azuredevops/AZURE_PIPELINES/DEPLOY/UI-TESTS/puppeteer.yml
  parameters:
    name: 'puppeteer'
    display_name: 'Puppeteer'
    source_directory: '$(Build.SourcesDirectory)/source/ui-tests/puppeteer'
    branch_name: 'main'
