version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "main"
    rebase-strategy: "auto"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    assignees:
      - "octocat"
    schedule:
      interval: daily
      time: "23:00"
    labels:
      - "dependencies"
    commit-message:
      prefix: "build"
      include: "scope"
    groups:
      commit_lint:
        patterns:
        - "@commitlint*"
        update-types:
        - "major"
        - "minor"
        - "patch"

  - package-ecosystem: "nuget"
    directory: "/source/notification-service"
    target-branch: "main"
    rebase-strategy: "auto"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    assignees:
      - "octocat"
    schedule:
      interval: daily
      time: "23:00"
    labels:
      - "dependencies"
    commit-message:
      prefix: "build"
      include: "scope"
    groups:
      angular:
        patterns:
        - "@commitlint*"
        update-types:
        - "major"
        - "minor"
        - "patch"

  - package-ecosystem: "npm"
    directory: "/source/progressive-web-app"
    target-branch: "main"
    rebase-strategy: "auto"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    assignees:
      - "octocat"
    schedule:
      interval: daily
      time: "23:00"
    labels:
      - "dependencies"
    commit-message:
      prefix: "build"
      include: "scope"
    groups:
      angular:
        patterns:
        - "@angular/*"
        - "@angular-devkit/*"
        update-types:
        - "major"
        - "minor"
        - "patch"
      microsoft:
        patterns:
        - "@azure*"
        - "@microsoft*"
        - "typescript*"
        update-types:
        - "major"
        - "minor"
        - "patch"
      ngneat:
        patterns:
        - "@ngneat/*"
        update-types:
        - "major"
        - "minor"
        - "patch"
      lint:
        patterns:
        - "@angular-eslint/*"
        - "@typescript-eslint/*"
        - "prettier*"
        - "eslint-*"
        update-types:
        - "major"
        - "minor"
        - "patch"
      test:
        patterns:
        - "karma*"
        - "@types/*"
        - "jasmine*"
        update-types:
        - "major"
        - "minor"
        - "patch"
  - package-ecosystem: "npm"
    directory: "/source/ui-tests/puppeteer"
    target-branch: "main"
    rebase-strategy: "auto"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    assignees:
      - "octocat"
    schedule:
      interval: daily
      time: "23:00"
    labels:
      - "dependencies"
    commit-message:
      prefix: "build"
      include: "scope"
