changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes
      labels:
        - major        
    - title: New Features
      labels:
        - enhancement        
    - title: Bug
      labels:
        - bug
    - title: Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
