name: $(Year:yyyy).$(Month).$(DayOfMonth).$(rev:r)

resources:
- repo: self
  clean: true

trigger:
  batch: true
  branches:
    include:
    - main
    - feature/*
    - bug/*        
  paths:
    include:
    - source/progressive-web-app        

pr:
  autoCancel: true
  branches:  
    include:
    - main  
  paths:
    include:
    - source/progressive-web-app
  drafts: true

variables:
  - group: 'Progressive Web Application'

stages:

- template: ../../.azuredevops/azure-pipelines/build/angular.yml
  parameters:
    name: build
    display_name: 'Build'
    source_directory: '$(Build.SourcesDirectory)/source/progressive-web-app'
    branch_name: 'main'

- template: ../../.azuredevops/azure-pipelines/deploy/angular.yml
  parameters:
    name: 'development'
    display_name: 'Development'
    depends_on: 'build'    
    environment_name: 'app-msaccprofinfo-dev-001'
    branch_name: 'main'
    main_project: "progressive.web.app"
