name: $(Year:yyyy).$(Month).$(DayOfMonth).$(rev:r)

resources:
  pipelines:
  - pipeline: puppeteer
    source: \microsoft-account-profile-information\puppeteer
    trigger: 
      branches:
        include: 
        - main

trigger: none

pr: none

stages:

- template: ../../.azuredevops/azure-pipelines/common/tagging.yml
  parameters:
    name: 'tagging'
    display_name: 'Tagging'
    branch_name: 'main'
