parameters:
  name: ''
  pool: ''
  display_name: ''
  environment_name: ''
  depends_on: ''
  
jobs:

- deployment: ${{ parameters.name }}
  displayName: ${{ format('{0}', parameters.display_name) }}
  environment: ${{ format('{0}', parameters.environment_name) }}
  pool: ${{ parameters.pool }}  
  continueOnError: 'false'
  dependsOn: ${{ parameters.depends_on }}
  strategy:
    runOnce:
      deploy:  
        steps:
          
        - task: AzureFunctionApp@1
          displayName: 'Azure Function'
          inputs:
            azureSubscription: 'Azure MPN'
            appType: 'functionApp'
            appName: 'ms-account-profile-info-notification-service-fa'
            package: '$(Pipeline.Workspace)/Drop/MSAccountPushSubscription.zip'
            deploymentMethod: 'auto'

        - powershell: |
            (Get-Content -Path .\ngsw.json -Raw:$true).replace("#RELEASE_NUMBER#", '$(Build.BuildNumber)') | Set-Content .\ngsw.json
          displayName: Files
          workingDirectory: '$(Pipeline.Workspace)/Drop'

        - task: AzureCLI@1
          displayName: 'Clean Angular Application'
          inputs:
            azureSubscription: 'Azure MPN'
            scriptLocation: inlineScript
            inlineScript: 'az storage blob delete-batch --source $(BlobContainerName) --account-name $(StorageAccountName) --pattern *.* --output table'
            workingDirectory: '$(Pipeline.Workspace)/Drop'

        - task: AzureFileCopy@2
          displayName: 'Deploy Angular Application'
          inputs:
            SourcePath: '$(Pipeline.Workspace)/Drop'
            azureSubscription: 'Azure MPN'
            Destination: AzureBlob
            storage: '$(StorageAccountName)'
            ContainerName: '$(BlobContainerName)'

        - task: AzureCLI@1
          displayName: 'Clean Notification Service Package'
          inputs:
            azureSubscription: 'Azure MPN'
            scriptLocation: inlineScript
            inlineScript: |
             call az storage blob delete-batch --source $(BlobContainerName) --account-name $(StorageAccountName) --pattern *.zip --output table
             call az storage blob delete-batch --source $(BlobContainerName) --account-name $(StorageAccountName) --pattern *.config --output table
             call az storage blob delete-batch --source $(BlobContainerName) --account-name $(StorageAccountName) --pattern *.map.gz --output table
             call az storage blob delete-batch --source $(BlobContainerName) --account-name $(StorageAccountName) --pattern *.parameters.json --output table
             call az storage blob delete-batch --source $(BlobContainerName) --account-name $(StorageAccountName) --pattern *deploy.json --output table
            workingDirectory: '$(Pipeline.Workspace)/Drop'
