parameters:
  name: ''
  pool: ''
  display_name: ''
  depends_on: 'Deployment'
  

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.display_name }}
  pool: ${{ parameters.pool }}
  continueOnError: false
  dependsOn: ${{ parameters.depends_on }}
  workspace:
    clean: all
  
  steps:
    
    - checkout: 'none'
    
    - task: ms-appinsights.appinsightsreleaseannotations.release-task.ms-appinsights.ReleaseAnnotation@1
      displayName: Stamp
      inputs:
        applicationId: '$(ApplicationId)'
        apiKey: '$(ApplicationKey)'

