export const environment = {
    production: true,
    PWASubscribeUrl: 'https://ms-account-profile-info-notification-service.azurewebsites.net/api/SubscriptionTriggerSubscribe?code=CfDJ8AAAAAAAAAAAAAAAAAAAAACnscspKKpSKmUbEb8KgUitHfVIoErvKf44rsecKkTMHsdteerbkVgaKSZYYYXvpltqFzZGRt8tq6MMxK3iKJpi1VRinAmFZNtN3Vx0uuYqgliu2NBedDWfzPruBUM6xy-pfLzbRDCuS9QkyKKjjtL9S5FUpvx00TuIGJntclPYrQ',
    PWAUnSubscribeUrl: 'https://ms-account-profile-info-notification-service.azurewebsites.net/api/SubscriptionTriggerUnSubscribe?code=CfDJ8AAAAAAAAAAAAAAAAAAAAADUPFk9C6LUkFEhyJcTxgXDl68tqZxf6QppOome88XSiUSexxrgBNFFYqqh9UbZONKm0csVnwqA4vLQQbm-t1a2JPhYIulLJf-QTyJ0ZFyUhn4yrQtB298j8im5qtpqfTEOi1pbDwuzqVj2PPgtE7CmpdBK4YatS-wEidYbZgESwQ'
};
