name: $(Year:yyyy).$(Month).$(DayOfMonth).$(rev:r)

resources:
- repo: self
  clean: true

trigger:
  batch: true
  branches:
    include:
    - main
    - feature/*
    - bug/*        
  paths:
    include:
    - source/notification-service        

pr:
  autoCancel: true
  branches:  
    include:
    - main  
  paths:
    include:
    - source/notification-service
  drafts: true

stages:

- template: ../../.azuredevops/azure-pipelines/build/azure-function.yml
  parameters:
    name: build
    display_name: 'Build'
    source_directory: '$(Build.SourcesDirectory)/source/notification-service'
    branch_name: 'main'
    main_project: "ms.account.push.subscription.func"

- template: ../../.azuredevops/azure-pipelines/deploy/azure-function.yml
  parameters:
    name: 'development'
    display_name: 'Development'
    depends_on: 'build'    
    environment_name: 'app-msaccprofinfo-dev-001'
    branch_name: 'main'
    main_project: "ms.account.push.subscription.func"