# Up
# docker-compose --file docker-compose.yml -p azure-cosmosdb-emulator up --force-recreate --build --remove-orphans

# Down
# docker-compose --file docker-compose.yml -p azure-cosmosdb-emulator down --rmi all
version: '3.4'

services:
  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    container_name: azure.cosmosdb
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=5 
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=false
      - AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1
    ports:
      - 8081:8081 
      - 10251:10251 
      - 10252:10252 
      - 10253:10253 
      - 10254:10254
